import "./globals.css";
import { Inter } from "next/font/google";
import { Sidebar } from "./Sidebar";

import { ClerkProvider, UserButton } from "@clerk/nextjs";
import { SidebarButtons } from "@/components/SidebarButtons";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={
            inter.className + " w-full h-screen relative flex z-0"
          }
        >
          <nav className="flex-shrink-0 overflow-x-hidden bg-gray-900 w-1/5 text-white">
            <SidebarButtons />
            <Sidebar />
          </nav>
          <main className="flex-grow">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
